#!/usr/bin/env bash

# Check if running with sudo
if [ "$(id -u)" -ne 0 ]; then
  echo "This script requires sudo privileges. Re-running with sudo..."
  # Using sudo with absolute path to ensure it works properly
  sudo "$(readlink -f "$0")" "$@"
  exit $?
fi

echo "STARTING THE INSTALLATION OF CHAOTIC-AUR"

set -euo pipefail

sudo pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
sudo pacman-key --lsign-key 3056513887B78AEB

sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst'
sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'

# Configure SSH agent in Zsh config
if [ -f "/etc/pacman.conf" ] && ! grep -q "chaotic-aur" "/etc/pacman.conf"; then
  echo "mirrorlist SSH agent to /etc/pacman.conf ..."
  cat >>"/etc/pacman.conf " <<'EOF'
[chaotic-aur]
Include = /etc/pacman.d/chaotic-mirrorlist 
EOF
else
  echo "already configured"
fi

sudo pacman --noconfirm -Syu
