#!/usr/bin/env bash

Wall_DIR="$HOME/Wallpapers/Pictures"

CWD="$(pwd)"

cd "$Wall_DIR" || exit

IFS=$'\n'

SELECTED_WALL=$(for a in *.jpg *.png *.jpeg; do echo -en "$a\0icon\x1f$a\n"; done | rofi -dmenu -p "")

if [ -n "$SELECTED_WALL" ]; then
  FULL_PATH="$Wall_DIR/$SELECTED_WALL"
  bash $HOME/sqtile/scripts/wset-backend "$FULL_PATH"
fi

cd "$CWD" || exit
