#!/usr/bin/env bash

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <path_to_image"
  exit 1
fi

IMAGE="$1"

notify-send "Changing Theme" "Applying new wallpaper and updating colors, please wait until confirmation..."

feh --bg-fill "$IMAGE"

wal -i "$IMAGE" -n -s -t -e

# python3 "$HOME/.config/nvim/pywal/chadwal.py"

qtile cmd-obj -o cmd -f reload_config
bash $HOME/sqtile/scripts/ref-dunst

notify-send "Theme Applied" "Wallpaper and Theme updated successfully"
